apiVersion: v1
kind: Service
metadata:
  name: quiz-mongo
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.database.service.type }}
  selector:
    app: quiz-mongo
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
